const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const ts = require('typescript');
const api = {};
vm.runInNewContext(ts.transpileModule(fs.readFileSync('services/redcoinsReminders.ts', 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022, esModuleInterop: true } }).outputText, { exports: api, Date, require: id => id === 'react-native' ? { Platform: { OS: 'web' } } : {} });
const now = new Date('2026-10-07T12:00:00+08:00');
const due = new Date('2026-10-22T08:51:00+08:00').toISOString();
const fixture = (automaticLog = false, extra = {}) => ({
  entries: [], deletedEntries: [], accounts: [{ name: 'Bank', balance: 1000 }, { name: 'Loan', balance: -2000 }],
  reminders: [{ id: 'r', enabled: true, automaticLog, startDate: due, frequency: 'monthly', repeatEvery: 1, endType: 'occurrences', occurrences: 2, template: { item: 'Loan payment', type: 'expense', amount: 100.13, account: 'Bank', category: 'Bills', subcategory: 'Loan' }, ...extra }],
});

for (const automatic of [false, true]) test(`early Log now consumes exactly one occurrence; auto mode ${automatic}`, () => {
  const original = fixture(automatic), before = JSON.stringify(original);
  const { state, entry } = api.logReminderOccurrenceNow(original, 'r', due, now);
  assert.equal(JSON.stringify(original), before);
  assert.equal(entry.date, now.toISOString()); assert.equal(entry.scheduledFor, due);
  assert.equal(entry.balanceEffectApplied, true); assert.equal(entry.autoGenerated, false);
  assert.equal(state.accounts[0].balance, 899.87); assert.equal(state.entries.length, 1);
  assert.equal(state.reminders[0].startDate, due); assert.equal(state.reminders[0].occurrences, 2);
  const remaining = api.reminderOccurrenceDates(state.reminders[0], now);
  assert.equal(remaining.length, 1); assert.equal(remaining[0].getDate(), 22); assert.equal(remaining[0].getMonth(), 10);
  assert.equal(api.materializeAutomaticReminders(state, new Date(due)).length, 0);
  assert.throws(() => api.logReminderOccurrenceNow(state, 'r', due, now), /already been logged/);
});

test('one-off schedule completes, and deleting its early entry cannot recreate it at due time', () => {
  const { state } = api.logReminderOccurrenceNow(fixture(true, { occurrences: 1 }), 'r', due, now);
  assert.equal(api.pendingReminderOccurrence(state, state.reminders[0], now), null);
  state.entries = [];
  assert.equal(api.materializeAutomaticReminders(state, new Date(due)).length, 0);
});

test('early transfer changes both balances once and retains its original recurring anchor', () => {
  const original = fixture(true); original.reminders[0].template.type = 'transfer'; original.reminders[0].template.toAccount = 'Loan';
  const { state } = api.logReminderOccurrenceNow(original, 'r', due, now);
  assert.equal(state.accounts[0].balance, 899.87); assert.equal(state.accounts[1].balance, -1899.87);
  assert.equal(state.reminders[0].startDate, due);
});

test('invalid, paused, stale or missing-account schedules fail without mutating the saved state', () => {
  for (const alter of [s => { s.reminders[0].enabled = false; }, s => { s.reminders[0].template.amount = 0; }, s => { s.accounts = []; }, s => { s.reminders[0].template.type = 'transfer'; s.reminders[0].template.toAccount = 'Bank'; }]) {
    const original = fixture(); alter(original); const before = JSON.stringify(original);
    assert.throws(() => api.logReminderOccurrenceNow(original, 'r', due, now)); assert.equal(JSON.stringify(original), before);
  }
  assert.throws(() => api.logReminderOccurrenceNow(fixture(), 'r', now.toISOString(), now), /changed/);
});

test('weekend adjustment consumes the moved due slot, not the following monthly slot', () => {
  const original = fixture(true, { startDate: '2026-10-24T08:51:00+08:00', excludeWeekend: true, weekendMove: 'before' });
  const first = api.pendingReminderOccurrence(original, original.reminders[0], now);
  assert.equal(first.getDay(), 5);
  const { state } = api.logReminderOccurrenceNow(original, 'r', first.toISOString(), now);
  const dates = api.reminderOccurrenceDates(state.reminders[0], now);
  assert.equal(dates.length, 1); assert.equal(dates[0].getMonth(), 10); assert.equal(dates[0].getDate(), 24);
});
