import type { FoodEntry, ActivityEntry, WeightEntry } from '../types';

export const progressDate = (key: string) => {
  const parts = key.split('/').map(Number);
  return new Date(parts[2], parts[1] - 1, parts[0]).getTime();
};
export function progressReportData(food: FoodEntry[], activities: ActivityEntry[], weights: WeightEntry[], period: '7' | '30' | 'all', now = new Date()) {
  const end = new Date(now); end.setHours(23, 59, 59, 999);
  const start = new Date(now); start.setHours(0, 0, 0, 0); start.setDate(start.getDate() - (period === '30' ? 29 : 6));
  const include = (row: { date: string }) => { const time = progressDate(row.date); return Number.isFinite(time) && time <= end.getTime() && (period === 'all' || time >= start.getTime()); };
  const order = (a: { date: string }, b: { date: string }) => progressDate(a.date) - progressDate(b.date);
  const meals = food.filter(include).sort(order), movement = activities.filter(include).sort(order), body = weights.filter(include).sort(order);
  const days = new Map<string, { date: string; eaten: number; burned: number; meals: number }>();
  meals.forEach((row) => { const day = days.get(row.date) || { date: row.date, eaten: 0, burned: 0, meals: 0 }; day.eaten += Number(row.calories) || 0; day.meals++; days.set(row.date, day); });
  movement.forEach((row) => { const day = days.get(row.date) || { date: row.date, eaten: 0, burned: 0, meals: 0 }; day.burned += Number(row.caloriesBurned) || 0; days.set(row.date, day); });
  return { meals, movement, body, days: [...days.values()].sort(order), period };
}
export function buildProgressReport(data: ReturnType<typeof progressReportData>, goal: number) {
  const esc = (value: unknown) => String(value ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]!));
  const num = (value: number) => Math.round(value).toLocaleString('en-MY');
  const total = data.days.reduce((sum, day) => sum + day.eaten, 0), burned = data.days.reduce((sum, day) => sum + day.burned, 0);
  const mealDays = data.days.filter((day) => day.meals > 0).length;
  const dates = [...data.days.map((row) => row.date), ...data.body.map((row) => row.date)].sort((a, b) => progressDate(a) - progressDate(b));
  const range = dates.length ? `${esc(dates[0])} - ${esc(dates[dates.length - 1])}` : 'No recorded days';
  const label = data.period === 'all' ? 'All history' : `Last ${data.period} days`;
  const chunks = <T,>(rows: T[], size: number) => Array.from({ length: Math.ceil(rows.length / size) }, (_, i) => rows.slice(i * size, (i + 1) * size));
  const page = (title: string, content: string, kicker = 'PROGRESS / LEANLOG') => `<section class="page"><div class="kicker">${kicker}</div><h1>${title}</h1>${content}<footer>LeanLog · ${label} · ${range}</footer></section>`;
  const bars = data.days.slice(-14).map((day) => `<div class="barrow"><span>${esc(day.date)}</span><div class="track"><div style="width:${Math.min(100, day.eaten / Math.max(goal, ...data.days.slice(-14).map((d) => d.eaten), 1) * 100)}%"></div></div><b>${num(day.eaten)}</b></div>`).join('');
  const delta = data.body.length > 1 ? data.body[data.body.length - 1].weight - data.body[0].weight : null;
  const overview = page('Read the pattern.', `<p class="intro">${label} / ${range}</p><div class="hero"><span>AVERAGE INTAKE / LOGGED FOOD DAYS</span><strong>${num(mealDays ? total / mealDays : 0)} <small>kcal</small></strong><p>${mealDays} food days logged · Daily target ${num(goal)} kcal</p></div><div class="stats"><div><b>${num(burned)}</b><span>kcal activity recorded</span></div><div><b>${data.movement.length}</b><span>activities logged</span></div><div><b>${delta === null ? '—' : `${delta > 0 ? '+' : ''}${delta.toFixed(1)} kg`}</b><span>recorded weight change</span></div></div><h2>Your recent rhythm</h2><p class="muted">Intake for the latest 14 recorded days within this selection. Missing records are not assumed to be zero intake.</p>${bars || '<p>No meals or activities recorded.</p>'}`);
  const daily = chunks(data.days, 20).map((rows, i) => page('The daily picture.', `<p class="intro">Daily totals · Part ${i + 1}</p><table><thead><tr><th>Date</th><th>Intake</th><th>Activity</th><th>Net kcal</th></tr></thead><tbody>${rows.map((r) => `<tr><td>${esc(r.date)}</td><td>${num(r.eaten)}</td><td>${num(r.burned)}</td><td>${num(r.eaten - r.burned)}</td></tr>`).join('')}</tbody></table><p class="muted">Net = recorded intake minus recorded activity. This is not a measurement of total daily energy expenditure.</p>`)).join('');
  const meals = chunks(data.meals, 15).map((rows, i) => page('At the table.', `<p class="intro">Meal journal · Part ${i + 1} · ${data.meals.length} records in selection</p>${rows.map((r) => `<div class="entry"><b>${esc(r.name)}</b><strong>${num(r.calories)} kcal</strong><p>${esc(r.date)} · ${esc(r.time)} · ${esc(r.category)}</p></div>`).join('')}`)).join('');
  const activities = chunks(data.movement, 15).map((rows, i) => page('Time in motion.', `<p class="intro">Activity journal · Part ${i + 1}</p>${rows.map((r) => `<div class="entry"><b>${esc(r.name)}</b><strong>${num(r.caloriesBurned)} kcal</strong><p>${esc(r.date)} · ${esc(r.time)} · ${num(r.duration)} min</p></div>`).join('')}`)).join('');
  const weights = chunks(data.body, 20).map((rows, i) => page('Body, over time.', `<p class="intro">Weight journal · Part ${i + 1}</p><table><thead><tr><th>Date</th><th>Weight</th><th>Note</th></tr></thead><tbody>${rows.map((r) => `<tr><td>${esc(r.date)}</td><td>${r.weight.toFixed(1)} kg</td><td>${esc(r.note)}</td></tr>`).join('')}</tbody></table>`)).join('');
  return `<!DOCTYPE html><html><head><meta charset="UTF-8"><style>@page{size:A4;margin:16mm}*{box-sizing:border-box}body{margin:0;color:#172033;font:12px Arial,sans-serif}.page{break-before:page;position:relative}.page:first-child{break-before:auto}.kicker{color:#d65840;font-size:10px;font-weight:bold;letter-spacing:2px}h1{font: bold 38px Georgia,serif;margin:12px 0}h2{font: bold 23px Georgia,serif;margin-top:24px}.intro,.muted{color:#737a84;line-height:1.5}.hero{background:#172033;color:#fff4db;padding:24px;border-radius:20px;margin:22px 0}.hero span{color:#91dcbb;font-size:10px;letter-spacing:1px}.hero strong{display:block;font: bold 48px Georgia,serif;margin:12px 0}.hero small{font:16px Arial}.hero p{color:#b4bfcb}.stats{display:flex;gap:10px}.stats div{flex:1;background:#f5eedf;border-radius:13px;padding:14px}.stats b{display:block;font: bold 22px Georgia,serif}.stats span{display:block;font-size:10px;margin-top:8px;color:#737a84}.barrow{display:flex;align-items:center;gap:12px;margin:12px 0}.barrow span{width:78px;font-size:10px}.barrow b{width:44px;text-align:right}.track{flex:1;background:#efe6d6;height:9px;border-radius:5px}.track div{height:9px;background:#e56245;border-radius:5px}table{width:100%;border-collapse:collapse;margin-top:18px}th{text-align:left;background:#f5eedf;font-size:10px;padding:10px}td{padding:10px;border-bottom:1px solid #e4ded3;overflow-wrap:anywhere}tr,.entry{break-inside:avoid}.entry{padding:13px 0;border-bottom:1px solid #e4ded3}.entry b{display:inline-block;max-width:72%;overflow-wrap:anywhere}.entry strong{float:right;color:#d65840}.entry p{color:#737a84;margin:6px 0 0;font-size:10px}footer{margin-top:24px;padding-top:12px;border-top:1px solid #e4ded3;color:#737a84;font-size:9px}</style></head><body>${overview}${daily}${meals}${activities}${weights}</body></html>`;
}
