import AsyncStorage from '@react-native-async-storage/async-storage';
import * as FileSystem from 'expo-file-system/legacy';
import * as Sharing from 'expo-sharing';
import type { BluecoinsSummary } from './bluecoins';
import { materializeAutomaticReminders } from './redcoinsReminders';
import { deliverExport } from './exportFile';
import { loadSpendingGuards, syncPinnedGuardSnapshot, WIDGET_CASH_REALITY_KEY } from './spendingGuards';
import { emitRedCoinsChange } from './redcoinsEvents';
import { buildRedCoinsSummary } from './redcoinsSummary';
import { prepareRedCoinsImport } from './redcoinsImportPlan';
import { migrateAccountPreferences } from './redcoinsAccountIdentity';
import { repairLegacyBluecoinsStatuses } from './redcoinsStatus';
import { cloneRedCoinsState, hasRedCoinsSqlData, markRedCoinsRevision, readRedCoinsSql, saveRedCoinsRecovery, writeRedCoinsSql } from './redcoinsSqlStore';

let stateWrites: Promise<void> = Promise.resolve();
export async function flushRedCoinsWrites() { await stateWrites; }
export const hasSavedRedCoins = hasRedCoinsSqlData;
/** JSON is now an export/preview format only; audits do not catch up schedules. */
export async function readSavedRedCoinsRaw() {
  await stateWrites;
  const state = await readRedCoinsSql(false);
  return state ? JSON.stringify(state) : null;
}
const lookupKey = (value?: string) => (value || '').trim().toLocaleLowerCase();
const SYSTEM_CATEGORY_KEYS = new Set(['(new account)', '(no category)', '(transfer)']);
const isUserCategory = (name?: string) => !SYSTEM_CATEGORY_KEYS.has(lookupKey(name));

export type RedCoinsType = 'expense' | 'income' | 'transfer';
export type RedCoinsAccountType = 'Bank' | 'Cash' | 'Credit card' | 'Liability' | 'Investment';
export type RedCoinsReminderFrequency = 'daily' | 'weekly' | 'monthly' | 'yearly';
export type RedCoinsReminderEndType = 'never' | 'date' | 'occurrences';
export type RedCoinsWeekendMove = 'before' | 'after';
export interface RedCoinsAccount {
  id: string;
  sourceAccountId?: string;
  name: string;
  type: RedCoinsAccountType;
  balance: number;
  cutOffDay?: number;
  dueDay?: number;
  editedAt?: string;
  limit?: number;
  icon?: string;
}
export interface RedCoinsCategory {
  id: string;
  name: string;
  icon: string;
  subcategories: string[];
  subcategoryIcons?: Record<string, string>;
  subcategoryTypes?: Record<string, Array<'income' | 'expense'>>;
}
export interface RedCoinsEntry {
  id: string;
  type: RedCoinsType;
  item: string;
  amount: number;
  date: string;
  account: string;
  toAccount?: string;
  sourceAccountId?: string;
  sourceToAccountId?: string;
  category: string;
  subcategory: string;
  note?: string;
  labels?: string[];
  status?: 'none' | 'cleared' | 'pending' | 'reconciled' | 'void';
  sourceStatus?: number;
  statusMappingVersion?: 1;
  legacyStatusUnknown?: boolean;
  repeat?: 'none' | 'daily' | 'weekly' | 'monthly' | 'yearly' | 'installment';
  installments?: number;
  reminderSeriesId?: string;
  reminderOccurrenceKey?: string;
  autoGenerated?: boolean;
  loggedAt?: string;
  /** Optional income attribution month, independent of actual cash-flow date. */
  incomePeriod?: string;
  scheduledFor?: string;
  split?: string;
  attachment?: string;
  origin?: 'bluecoins' | 'redcoins';
  exportedAt?: string;
  editedAt?: string;
  balanceEffectApplied?: boolean;
  reconciledImportId?: string;
  /** Explicit copy, not an accidental duplicate to merge with its source. */
  duplicateOfId?: string;
}
export interface RedCoinsReminder {
  id: string;
  enabled: boolean;
  automaticLog: boolean;
  frequency: RedCoinsReminderFrequency;
  repeatEvery: number;
  startDate: string;
  endType: RedCoinsReminderEndType;
  endDate?: string;
  occurrences?: number;
  excludeWeekend: boolean;
  weekendMove: RedCoinsWeekendMove;
  createdAt: string;
  template: Omit<RedCoinsEntry, 'id' | 'date' | 'repeat' | 'installments' | 'balanceEffectApplied' | 'reminderSeriesId' | 'reminderOccurrenceKey' | 'autoGenerated'>;
  notificationIds?: string[];
  consumedOccurrenceKeys?: string[];
}
export interface RedCoinsExportBatch {
  id: string;
  createdAt: string;
  entryIds: string[];
  confirmedAt?: string;
}
export type RedCoinsDeletion = Pick<RedCoinsEntry, 'id' | 'type' | 'item' | 'amount' | 'date' | 'account' | 'reconciledImportId' | 'duplicateOfId' | 'exportedAt'>;
export interface RedCoinsState {
  storageVersion?: 2;
  statusMappingVersion?: 1;
  importSnapshot?: { sourceName: string; sourceDate?: string; importedAt: string; entries: { id: string }[] };
  entries: RedCoinsEntry[];
  reminders: RedCoinsReminder[];
  accounts: RedCoinsAccount[];
  /** Home card only; undefined keeps legacy defaults, [] deliberately shows none. */
  favoriteAccountIds?: string[];
  bankReviews?: Record<string, import('./redcoinsReconciliation').BankReview>;
  categories: RedCoinsCategory[];
  /** Legacy v2.9.x recovery data. Migrated to compact deletion markers on load. */
  trash?: RedCoinsEntry[];
  deletedEntries: RedCoinsDeletion[];
  payday: number;
  monthlyBudget: number;
  safetyBuffer: number;
  importedSource?: string;
  createdAt: string;
  exportBatches: RedCoinsExportBatch[];
  subcategoryBudgets: Record<string, number>;
  termBudgets?: import('./redcoinsTermBudget').TermBudget[];
  analysisExpenseClasses?: Record<string, 'protected' | 'flexible' | 'unconfirmed'>;
  deletedAccountNames?: string[];
  deletedSourceAccountIds?: string[];
  deletedCategoryNames?: string[];
  deletedSubcategories?: Record<string, string[]>;
  reportPreferences?: {
    mode: 'salary-cycle' | 'custom';
    salarySource: string;
    customStart: string;
    customEnd: string;
  };
  entryDefaults?: Partial<
    Record<
      RedCoinsType,
      {
        account: string;
        toAccount?: string;
        category: string;
        subcategory: string;
      }
    >
  >;
}

const id = () => `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;

function reconcileScheduledBalanceEffects(state: RedCoinsState) {
  let changed = false;
  state.entries
    .filter((entry) => entry.balanceEffectApplied != null || entry.origin !== 'bluecoins')
    .forEach((entry) => {
      const due = new Date(entry.date).getTime() <= Date.now();
      if (!due && entry.balanceEffectApplied !== false) {
        applyEntryBalance(state, entry, -1, true);
        entry.balanceEffectApplied = false;
        if (entry.autoGenerated) entry.status = 'pending';
        changed = true;
      }
      if (due && entry.balanceEffectApplied === false) {
        applyEntryBalance(state, entry, 1, true);
        entry.balanceEffectApplied = true;
        if (entry.autoGenerated) entry.status = 'cleared';
        changed = true;
      }
      if (due && entry.balanceEffectApplied == null) {
        entry.balanceEffectApplied = true;
        changed = true;
      }
    });
  return changed;
}

export function freshRedCoinsState(summary?: BluecoinsSummary | null): RedCoinsState {
  const accountMap = new Map<string, RedCoinsAccount>();
  summary?.redcoins.accounts.forEach((a) => accountMap.set(a.name, { id: id(), ...a }));
  const categories = (summary?.redcoins.categories || []).filter(({ name }) => isUserCategory(name)).map(({ name, subcategories, subcategoryTypes }, index) => ({
    id: id(),
    name,
    icon: ['▰', '●', '⛽', '🍴', '⌂', '♥', '✈', '⌁'][index % 8],
    subcategories,
    subcategoryTypes,
  }));
  return {
    entries: summary?.redcoins.entries || [],
    reminders: [],
    accounts: [...accountMap.values()],
    categories,
    deletedEntries: [],
    exportBatches: [],
    subcategoryBudgets: {},
    deletedAccountNames: [],
    deletedCategoryNames: [],
    deletedSubcategories: {},
    entryDefaults: {},
    reportPreferences: undefined,
    payday: summary?.monthly.payday || 25,
    monthlyBudget: summary?.monthly.budget || 2000,
    safetyBuffer: summary?.cashReality.safetyBuffer || 0,
    importedSource: summary?.sourceName,
    createdAt: new Date().toISOString(),
  };
}

/** Ordinary opens read only durable RedCoins data, never a Bluecoins baseline. */
export async function loadRedCoins(): Promise<RedCoinsState> {
  await stateWrites;
  const durable = await readRedCoinsSql();
  const saved = durable || freshRedCoinsState();
  if (!durable) markRedCoinsRevision(saved, 0);
  const originalStorageVersion = saved.storageVersion;
  const recoveryRaw = durable && (saved.storageVersion !== 2 || saved.statusMappingVersion !== 1) ? JSON.stringify(saved) : null;
  if (saved.storageVersion !== 2) {
    // One-time, byte-for-byte recovery checkpoint BEFORE any migration.
    // Never reconstruct balances from a FYDB or remove manual adjustments.
    if (recoveryRaw) await saveRedCoinsRecovery('redcoins_pre_authoritative_v1', recoveryRaw);
    saved.storageVersion = 2;
    saved.entries.forEach(entry => {
      // A legacy saved balance is the migration baseline. Missing flags are
      // not evidence that past source rows need replaying, even after backup day.
      if (entry.balanceEffectApplied == null) entry.balanceEffectApplied = new Date(entry.date).getTime() <= Date.now();
    });
    await AsyncStorage.setItem('bluecoins_auto_sync_v1', 'false');
  }
  saved.categories = (saved.categories || []).filter(category => isUserCategory(category.name));
  saved.reminders ||= [];
  saved.deletedEntries = collectDeletions(saved);
  saved.deletedAccountNames ||= [];
  saved.deletedCategoryNames ||= [];
  saved.deletedSubcategories ||= {};
  saved.exportBatches ||= [];
  saved.entryDefaults ||= {};
  saved.subcategoryBudgets ||= {};
  saved.payday ??= Number(await AsyncStorage.getItem('bluecoins_payday_v1')) || 25;
  saved.monthlyBudget ??= Number(await AsyncStorage.getItem('bluecoins_monthly_budget_v1')) || 2000;
  saved.safetyBuffer ??= Math.max(0, Number(await AsyncStorage.getItem('bluecoins_cash_reality_buffer_v1')) || 0);
  if (!durable) {
    const budget = await AsyncStorage.getItem('bluecoins_monthly_budget_v1');
    const payday = await AsyncStorage.getItem('bluecoins_payday_v1');
    const buffer = await AsyncStorage.getItem('bluecoins_cash_reality_buffer_v1');
    if (budget != null && Number.isFinite(Number(budget))) saved.monthlyBudget = Math.max(0, Number(budget));
    if (payday != null && Number.isFinite(Number(payday))) saved.payday = Math.max(1, Math.min(28, Number(payday)));
    if (buffer != null && Number.isFinite(Number(buffer))) saved.safetyBuffer = Math.max(0, Number(buffer));
  }
  const generated = materializeAutomaticReminders(saved);
  const statusRepaired = repairLegacyBluecoinsStatuses(saved);
  if (statusRepaired && recoveryRaw) await saveRedCoinsRecovery('redcoins_pre_status_mapping_v1', recoveryRaw);
  const balanceChanged = reconcileScheduledBalanceEffects(saved);
  const { trash: _legacyTrash, ...normalized } = saved;
  if (!durable || originalStorageVersion !== 2 || statusRepaired || balanceChanged || generated.length) await saveRedCoins(normalized);
  return normalized;
}

/** Explicit import compatibility entrypoint; UI uses staged preview/commit below. */
export async function importRedCoins(summary: BluecoinsSummary) {
  const current = await loadRedCoins();
  const plan = prepareRedCoinsImport(current, summary);
  await migrateAccountPreferences(plan.aliases, plan.redirects);
  await saveRedCoins(plan.state);
  return plan.state;
}

/** Read settings only, not FYDB. Shared by every local dashboard consumer. */
export async function getRedCoinsSummary(current?: RedCoinsState, now = new Date()): Promise<BluecoinsSummary> {
  const state = current || await loadRedCoins();
  const [selectedRaw, initialized, fixedRaw, guards] = await Promise.all([
    AsyncStorage.getItem('bluecoins_cash_reality_accounts_v1'),
    AsyncStorage.getItem('bluecoins_cash_reality_accounts_initialised_v1'),
    AsyncStorage.getItem('bluecoins_fixed_commitments_v1'), loadSpendingGuards(),
  ]);
  let selectedAccounts: string[] = selectedRaw ? JSON.parse(selectedRaw) : [];
  if (initialized !== 'true' && !selectedRaw) {
    const candidates = state.accounts.filter(a => a.type === 'Bank' || a.type === 'Cash');
    const preferred = candidates.filter(a => ['aeon', 'cimb', 'maybank', 'rhb'].includes(lookupKey(a.name)));
    selectedAccounts = (preferred.length ? preferred : candidates).map(a => a.name);
    if (candidates.length) {
      await AsyncStorage.setItem('bluecoins_cash_reality_accounts_v1', JSON.stringify(selectedAccounts));
      await AsyncStorage.setItem('bluecoins_cash_reality_accounts_initialised_v1', 'true');
    }
  }
  const summary = buildRedCoinsSummary(state, { selectedAccounts, fixedCommitments: fixedRaw ? JSON.parse(fixedRaw) : [], guards }, now);
  await Promise.all([
    syncPinnedGuardSnapshot(summary.spendingGuards, summary.sourceDate),
    AsyncStorage.setItem(WIDGET_CASH_REALITY_KEY, JSON.stringify({ ...summary.cashReality, sourceDate: summary.sourceDate })),
  ]);
  return summary;
}

export const createRedCoinsDeletion = (entry: RedCoinsEntry): RedCoinsDeletion => ({
  id: entry.id,
  type: entry.type,
  item: entry.item,
  amount: entry.amount,
  date: entry.date,
  account: entry.account,
  reconciledImportId: entry.reconciledImportId,
  duplicateOfId: entry.duplicateOfId,
  exportedAt: entry.exportedAt,
});

const deletionIdentity = (entry: RedCoinsDeletion) => entry.reconciledImportId || entry.id || entrySignature(entry);
const collectDeletions = (state: RedCoinsState) => {
  const merged = [...(state.deletedEntries || []), ...(state.trash || []).map(createRedCoinsDeletion)];
  return [...new Map(merged.map((entry) => [deletionIdentity(entry), entry])).values()];
};

export const saveRedCoins = async (state: RedCoinsState, source?: object, entryIds?: string[]) => {
  const { trash: _legacyTrash, ...compact } = state;
  const snapshot = cloneRedCoinsState(compact);
  const write = stateWrites.catch(() => {}).then(async () => {
    const revision = await writeRedCoinsSql(snapshot, { entryIds });
    markRedCoinsRevision(state, revision);
  });
  stateWrites = write.catch(() => {});
  await write;
  emitRedCoinsChange('state', source);
};

/** Serialized compare-and-replace: restore must not clobber an intervening edit. */
export async function replaceRedCoinsFromBackup(state: RedCoinsState, expectedRaw: string, preferences: Record<string, string>, expectedPreferences: Record<string, string | null>) {
  const write = stateWrites.catch(() => {}).then(async () => {
    for (const [key, expected] of Object.entries(expectedPreferences)) if (await AsyncStorage.getItem(key) !== expected) throw new Error('RedCoins settings changed. Preview the backup again.');
    const revision = await writeRedCoinsSql(state, { expectedRaw, preferences });
    markRedCoinsRevision(state, revision);
  });
  stateWrites = write.catch(() => {});
  await write;
  emitRedCoinsChange('state');
  emitRedCoinsChange('guards');
}

const entrySignature = (entry: Pick<RedCoinsEntry, 'item' | 'amount' | 'date' | 'account'>) => `${entry.date.slice(0, 10)}|${entry.item.trim().toLowerCase()}|${entry.amount.toFixed(2)}|${entry.account.trim().toLowerCase()}`;

/** Compatibility name for older integrations; source is no longer authoritative. */
export async function mergeRedCoinsIntoBudgetCoach(_source: BluecoinsSummary): Promise<BluecoinsSummary> {
  return getRedCoinsSummary();
}

export function applyEntryBalance(state: RedCoinsState, entry: RedCoinsEntry, direction = 1, includeFuture = false) {
  if (!includeFuture && new Date(entry.date).getTime() > Date.now()) return;
  const source = state.accounts.find((a) => a.name === entry.account);
  const target = state.accounts.find((a) => a.name === entry.toAccount);
  if (entry.type === 'expense' && source) source.balance -= entry.amount * direction;
  if (entry.type === 'income' && source) source.balance += entry.amount * direction;
  if (entry.type === 'transfer') {
    if (source) source.balance -= entry.amount * direction;
    if (target) target.balance += entry.amount * direction;
  }
}

const csv = (value: unknown) => `"${String(value ?? '').replace(/"/g, '""')}"`;
const bluecoinsDate = (value: string) => {
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return value.slice(0, 10);
  return `${String(date.getMonth() + 1).padStart(2, '0')}/${String(date.getDate()).padStart(2, '0')}/${date.getFullYear()}`;
};
const bluecoinsAccountType = (state: RedCoinsState, accountName: string) => {
  const type = state.accounts.find((account) => account.name === accountName)?.type || 'Bank';
  return type === 'Credit card' ? 'Credit Card' : type;
};
const bluecoinsRow = (values: unknown[]) => values.map(csv).join(',');
export async function exportRedCoinsCsv(state: RedCoinsState, mode: 'pending' | 'all' = 'pending'): Promise<RedCoinsExportBatch | null> {
  // Bluecoins' standard CSV importer is positional, not header-driven.
  const header = ['Type', 'Date', 'Name', 'Amount', 'Category Parent', 'Category', 'Account Type', 'Account', 'Notes', 'Labels', 'Status', 'Split'];
  const selected = state.entries.filter((entry) => entry.origin !== 'bluecoins' && !entry.reconciledImportId && (!entry.autoGenerated || new Date(entry.date).getTime() <= Date.now()) && (mode === 'all' || !entry.exportedAt));
  if (!selected.length) {
    throw new Error('No new entries available for this export.');
  }
  const rows = selected.flatMap((entry) => {
    const type = entry.type[0].toUpperCase() + entry.type.slice(1);
    const date = bluecoinsDate(entry.date);
    const notes = [entry.note, `RedCoins time ${new Date(entry.date).toLocaleTimeString('en-MY', { hour: '2-digit', minute: '2-digit', hour12: false })}`].filter(Boolean).join(' · ');
    const exportStatus = entry.status === 'none' ? '' : entry.status || '';
    const common = [type, date, entry.item, entry.amount.toFixed(2)];
    if (entry.type !== 'transfer') return [bluecoinsRow([...common, entry.category, entry.subcategory, bluecoinsAccountType(state, entry.account), entry.account, notes, (entry.labels || []).join(' '), exportStatus, ''])];
    if (!entry.toAccount) return [];
    // Bluecoins represents a transfer as two adjacent rows: money out, then money in.
    return [bluecoinsRow(['Transfer', date, entry.item, (-entry.amount).toFixed(2), '(Transfer)', '(Transfer)', bluecoinsAccountType(state, entry.account), entry.account, notes, (entry.labels || []).join(' '), exportStatus, '']), bluecoinsRow(['Transfer', date, entry.item, entry.amount.toFixed(2), '(Transfer)', '(Transfer)', bluecoinsAccountType(state, entry.toAccount), entry.toAccount, notes, (entry.labels || []).join(' '), exportStatus, ''])];
  });
  const uri = `${FileSystem.cacheDirectory}RedCoins-to-Bluecoins-${new Date().toISOString().slice(0, 10)}.csv`;
  await FileSystem.writeAsStringAsync(uri, `\ufeff${[header.map(csv).join(','), ...rows].join('\r\n')}`);
  if (!await deliverExport(uri, uri.split('/').pop()!, 'text/csv')) return null;
  return {
    id: `export-${Date.now()}`,
    createdAt: new Date().toISOString(),
    entryIds: selected.map((entry) => entry.id),
  };
}

export function confirmRedCoinsExport(state: RedCoinsState, batchId: string): RedCoinsState {
  const confirmedAt = new Date().toISOString();
  const batch = state.exportBatches.find((item) => item.id === batchId);
  if (!batch) return state;
  return {
    ...state,
    entries: state.entries.map((entry) => (batch.entryIds.includes(entry.id) ? { ...entry, exportedAt: confirmedAt } : entry)),
    exportBatches: state.exportBatches.map((item) => (item.id === batchId ? { ...item, confirmedAt } : item)),
  };
}

export async function exportRedCoinsBackup(state: RedCoinsState) {
  const { captureRedCoinsBackup, getBackupFolderConfig, backupRedCoinsToFolder } = await import('./redcoinsBackupFiles');
  if ((await getBackupFolderConfig())?.folderUri) {
    await backupRedCoinsToFolder(true);
    return;
  }
  const uri = `${FileSystem.cacheDirectory}RedCoins-backup-${new Date().toISOString().slice(0, 10)}.json`;
  await FileSystem.writeAsStringAsync(
    uri,
    JSON.stringify(
      await captureRedCoinsBackup(state),
      null,
      2,
    ),
  );
  await deliverExport(uri, uri.split('/').pop()!, 'application/json');
}
