import type { RedCoinsEntry, RedCoinsReminder, RedCoinsState } from './redcoins';

let Notifications: any = null;
try { Notifications = require('expo-notifications'); } catch {}

const CHANNEL = 'redcoins-reminders';
const MAX_GENERATED_OCCURRENCES = 550;
const NEVER_HORIZON_MONTHS = 18;

const occurrenceKey = (seriesId: string, date: Date) => `${seriesId}:${date.toISOString()}`;

export function advanceReminderDate(date: Date, frequency: RedCoinsReminder['frequency'], repeatEvery = 1) {
  const next = new Date(date);
  const every = Math.max(1, Math.floor(repeatEvery || 1));
  if (frequency === 'daily') next.setDate(next.getDate() + every);
  if (frequency === 'weekly') next.setDate(next.getDate() + every * 7);
  if (frequency === 'monthly') {
    const day = next.getDate();
    next.setDate(1);
    next.setMonth(next.getMonth() + every);
    next.setDate(Math.min(day, new Date(next.getFullYear(), next.getMonth() + 1, 0).getDate()));
  }
  if (frequency === 'yearly') {
    const month = next.getMonth();
    const day = next.getDate();
    next.setDate(1);
    next.setFullYear(next.getFullYear() + every);
    next.setMonth(month);
    next.setDate(Math.min(day, new Date(next.getFullYear(), month + 1, 0).getDate()));
  }
  return next;
}

function moveWeekend(date: Date, reminder: RedCoinsReminder) {
  const moved = new Date(date);
  if (!reminder.excludeWeekend) return moved;
  if (moved.getDay() === 6) moved.setDate(moved.getDate() + (reminder.weekendMove === 'before' ? -1 : 2));
  if (moved.getDay() === 0) moved.setDate(moved.getDate() + (reminder.weekendMove === 'before' ? -2 : 1));
  return moved;
}

export function reminderOccurrenceDates(reminder: RedCoinsReminder, now = new Date()) {
  if (!reminder.enabled) return [];
  const dates: Date[] = [];
  const start = new Date(reminder.startDate);
  if (Number.isNaN(start.getTime())) return dates;
  const horizon = new Date(now);
  horizon.setMonth(horizon.getMonth() + NEVER_HORIZON_MONTHS);
  const explicitEnd = reminder.endDate ? new Date(reminder.endDate) : null;
  const max = reminder.endType === 'occurrences'
    ? Math.max(1, Math.min(MAX_GENERATED_OCCURRENCES, reminder.occurrences || 1))
    : MAX_GENERATED_OCCURRENCES;
  let cursor = start;
  if (reminder.endType === 'never') {
    const floor = new Date(now);
    floor.setHours(0, 0, 0, 0);
    for (let skipped = 0; cursor < floor && skipped < 10000; skipped += 1) {
      cursor = advanceReminderDate(cursor, reminder.frequency, reminder.repeatEvery);
    }
  }
  const unique = new Set<string>();
  for (let attempts = 0; attempts < MAX_GENERATED_OCCURRENCES * 7 && dates.length < max; attempts += 1) {
    if (reminder.endType === 'date' && explicitEnd && cursor > explicitEnd) break;
    if (reminder.endType === 'never' && cursor > horizon) break;
    const occurrence = moveWeekend(cursor, reminder);
    const key = occurrence.toISOString();
    if (!unique.has(key)) {
      unique.add(key);
      dates.push(occurrence);
    }
    cursor = advanceReminderDate(cursor, reminder.frequency, reminder.repeatEvery);
  }
  return dates;
}

export function materializeAutomaticReminders(state: RedCoinsState) {
  const existing = new Set(state.entries.map((entry) => entry.reminderOccurrenceKey).filter(Boolean));
  const deletedIds = new Set((state.deletedEntries || []).map((entry) => entry.id));
  const generated: RedCoinsEntry[] = [];
  state.reminders.filter((reminder) => reminder.enabled && reminder.automaticLog).forEach((reminder) => {
    const dates = reminderOccurrenceDates(reminder);
    let hasUpcoming = dates.some((date) => date.getTime() > Date.now() && existing.has(occurrenceKey(reminder.id, date)));
    for (const date of dates) {
      const key = occurrenceKey(reminder.id, date);
      if (existing.has(key)) continue;
      const generatedId = `reminder-${reminder.id}-${date.getTime()}`;
      if (deletedIds.has(generatedId)) continue;
      if (date.getTime() > Date.now() && hasUpcoming) break;
      existing.add(key);
      generated.push({
        ...reminder.template,
        id: generatedId,
        date: date.toISOString(),
        repeat: 'none',
        origin: 'redcoins',
        status: date.getTime() <= Date.now() ? 'cleared' : 'pending',
        // Reconciliation applies the balance exactly once when this occurrence
        // is due, including after the app has been closed across the due date.
        balanceEffectApplied: false,
        reminderSeriesId: reminder.id,
        reminderOccurrenceKey: key,
        autoGenerated: true,
      });
      if (date.getTime() > Date.now()) {
        hasUpcoming = true;
        break;
      }
    }
  });
  if (generated.length) state.entries = [...generated, ...state.entries].sort((a, b) => b.date.localeCompare(a.date));
  return generated;
}

export function nextReminderOccurrence(reminder: RedCoinsReminder, now = new Date()) {
  return reminderOccurrenceDates(reminder, now).find((date) => date.getTime() >= now.getTime()) || null;
}

export async function syncReminderNotifications(reminders: RedCoinsReminder[]) {
  if (!Notifications) return;
  const previousIds = reminders.flatMap((reminder) => reminder.notificationIds || []);
  await Promise.all(previousIds.map((id) => Notifications.cancelScheduledNotificationAsync(id).catch(() => {})));
  const permission = await Notifications.requestPermissionsAsync().catch(() => null);
  if (!permission?.granted) return;
  await Notifications.setNotificationChannelAsync(CHANNEL, {
    name: 'RedCoins reminders',
    importance: Notifications.AndroidImportance.HIGH,
    lockscreenVisibility: Notifications.AndroidNotificationVisibility.PUBLIC,
  });
  const now = Date.now();
  for (const reminder of reminders) {
    reminder.notificationIds = [];
    if (!reminder.enabled) continue;
    const upcoming = reminderOccurrenceDates(reminder).filter((date) => date.getTime() > now).slice(0, 20);
    for (const date of upcoming) {
      const notificationId = await Notifications.scheduleNotificationAsync({
        content: {
          title: reminder.automaticLog ? 'Transaction auto-logged' : 'Transaction due',
          body: `${reminder.template.item} · RM ${reminder.template.amount.toFixed(2)} · ${reminder.template.account}`,
          data: { screen: 'RedCoins', section: 'plan', reminderId: reminder.id },
          sound: true,
        },
        trigger: { type: 'date', date, channelId: CHANNEL },
      }).catch(() => null);
      if (notificationId) reminder.notificationIds.push(notificationId);
    }
  }
}
