import type { RedCoinsAccount, RedCoinsEntry, RedCoinsReminder, RedCoinsState } from './redcoins';
import BluecoinsDriveReader from 'bluecoins-drive-reader';
import { Platform } from 'react-native';

let Notifications: any = null;
try { Notifications = require('expo-notifications'); } catch {}

const CHANNEL = 'redcoins-reminders';
const MAX_GENERATED_OCCURRENCES = 550;
const NEVER_HORIZON_MONTHS = 18;

const occurrenceKey = (seriesId: string, date: Date) => `${seriesId}:${date.toISOString()}`;

export function advanceReminderDate(date: Date, frequency: RedCoinsReminder['frequency'], repeatEvery = 1) {
  const next = new Date(date);
  const every = Math.max(1, Math.floor(repeatEvery || 1));
  if (frequency === 'daily') next.setDate(next.getDate() + every);
  if (frequency === 'weekly') next.setDate(next.getDate() + every * 7);
  if (frequency === 'monthly') {
    const day = next.getDate();
    next.setDate(1);
    next.setMonth(next.getMonth() + every);
    next.setDate(Math.min(day, new Date(next.getFullYear(), next.getMonth() + 1, 0).getDate()));
  }
  if (frequency === 'yearly') {
    const month = next.getMonth();
    const day = next.getDate();
    next.setDate(1);
    next.setFullYear(next.getFullYear() + every);
    next.setMonth(month);
    next.setDate(Math.min(day, new Date(next.getFullYear(), month + 1, 0).getDate()));
  }
  return next;
}

function moveWeekend(date: Date, reminder: RedCoinsReminder) {
  const moved = new Date(date);
  if (!reminder.excludeWeekend) return moved;
  if (moved.getDay() === 6) moved.setDate(moved.getDate() + (reminder.weekendMove === 'before' ? -1 : 2));
  if (moved.getDay() === 0) moved.setDate(moved.getDate() + (reminder.weekendMove === 'before' ? -2 : 1));
  return moved;
}

export function reminderOccurrenceDates(reminder: RedCoinsReminder, now = new Date()) {
  if (!reminder.enabled) return [];
  const dates: Date[] = [];
  const start = new Date(reminder.startDate);
  if (Number.isNaN(start.getTime())) return dates;
  const horizon = new Date(now);
  horizon.setMonth(horizon.getMonth() + NEVER_HORIZON_MONTHS);
  const explicitEnd = reminder.endDate ? new Date(reminder.endDate) : null;
  const max = reminder.endType === 'occurrences'
    ? Math.max(1, Math.min(MAX_GENERATED_OCCURRENCES, reminder.occurrences || 1))
    : MAX_GENERATED_OCCURRENCES;
  let cursor = start;
  const unique = new Set<string>();
  for (let attempts = 0; attempts < MAX_GENERATED_OCCURRENCES * 7 && dates.length < max; attempts += 1) {
    if (reminder.endType === 'date' && explicitEnd && cursor > explicitEnd) break;
    if (reminder.endType === 'never' && cursor > horizon) break;
    const occurrence = moveWeekend(cursor, reminder);
    const key = occurrence.toISOString();
    if (!unique.has(key)) {
      unique.add(key);
      dates.push(occurrence);
    }
    cursor = advanceReminderDate(cursor, reminder.frequency, reminder.repeatEvery);
  }
  return dates;
}

export function missingReminderAccounts(reminder: RedCoinsReminder, accounts: RedCoinsAccount[]) {
  const names = new Set(accounts.map(account => account.name));
  const required = [reminder.template.account, ...(reminder.template.type === 'transfer' ? [reminder.template.toAccount || 'Unknown destination'] : [])];
  return [...new Set(required.filter(name => !names.has(name)))];
}

export function materializeAutomaticReminders(state: RedCoinsState, now = new Date()) {
  // A schedule is not a transaction. Remove future placeholders created by
  // older builds; an auto-log row is materialized only once its due time has
  // actually arrived.
  state.entries = state.entries.filter((entry) => !entry.autoGenerated || new Date(entry.date).getTime() <= now.getTime());
  const existing = new Set(state.entries.map((entry) => entry.reminderOccurrenceKey).filter(Boolean));
  const deletedIds = new Set((state.deletedEntries || []).map((entry) => entry.id));
  const generated: RedCoinsEntry[] = [];
  state.reminders.filter((reminder) => reminder.enabled && reminder.automaticLog).forEach((reminder) => {
    // Do not create a half-transfer/debit when a deleted legacy account is
    // still referenced by a schedule. Keep the schedule available to repair.
    if (state.accounts && missingReminderAccounts(reminder, state.accounts).length) return;
    const dates = reminderOccurrenceDates(reminder, now);
    for (const date of dates) {
      if (date.getTime() > now.getTime()) break;
      const key = occurrenceKey(reminder.id, date);
      if (existing.has(key)) continue;
      const generatedId = `reminder-${reminder.id}-${date.getTime()}`;
      if (deletedIds.has(generatedId)) continue;
      existing.add(key);
      generated.push({
        ...reminder.template,
        id: generatedId,
        date: date.toISOString(),
        repeat: 'none',
        origin: 'redcoins',
        status: 'cleared',
        // Reconciliation applies the balance exactly once when this occurrence
        // is due, including after the app has been closed across the due date.
        balanceEffectApplied: false,
        reminderSeriesId: reminder.id,
        reminderOccurrenceKey: key,
        autoGenerated: true,
        loggedAt: now.toISOString(),
      });
    }
  });
  if (generated.length) state.entries = [...generated, ...state.entries].sort((a, b) => b.date.localeCompare(a.date));
  return generated;
}

export function nextReminderOccurrence(reminder: RedCoinsReminder, now = new Date()) {
  return reminderOccurrenceDates(reminder, now).find((date) => date.getTime() >= now.getTime()) || null;
}

export async function syncReminderNotifications(reminders: RedCoinsReminder[]) {
  if (!Notifications) return;
  const previousIds = reminders.flatMap((reminder) => reminder.notificationIds || []);
  await Promise.all(previousIds.map((id) => Notifications.cancelScheduledNotificationAsync(id).catch(() => {})));
  await Notifications.setNotificationChannelAsync(CHANNEL, {
    name: 'RedCoins reminders',
    importance: Notifications.AndroidImportance.HIGH,
    lockscreenVisibility: Notifications.AndroidNotificationVisibility.PUBLIC,
    sound: 'default',
  });
  const permission = await Notifications.getPermissionsAsync().catch(() => null);
  const now = Date.now();
  if (Platform.OS === 'android' && BluecoinsDriveReader?.replaceRedCoinsAlarmsAsync) {
    const alarms = reminders.flatMap((reminder) => reminderOccurrenceDates(reminder)
      .filter((date) => date.getTime() > now).slice(0, 20).map((date) => ({
        key: occurrenceKey(reminder.id, date), due: date.getTime(), automaticLog: reminder.automaticLog,
        body: `${reminder.template.item} · RM ${reminder.template.amount.toFixed(2)} · ${reminder.template.account} · Due ${date.toLocaleString('en-MY')}`,
      })));
    await BluecoinsDriveReader.replaceRedCoinsAlarmsAsync(JSON.stringify(alarms));
    return;
  }
  if (!permission?.granted) return;
  for (const reminder of reminders) {
    reminder.notificationIds = [];
    if (!reminder.enabled) continue;
    const upcoming = reminderOccurrenceDates(reminder).filter((date) => date.getTime() > now).slice(0, 20);
    for (const date of upcoming) {
      const notificationId = await Notifications.scheduleNotificationAsync({
        content: {
          title: reminder.automaticLog ? 'Auto-log due' : 'Transaction reminder',
          body: reminder.automaticLog
            ? `${reminder.template.item} · RM ${reminder.template.amount.toFixed(2)} · ${reminder.template.account} · Open LeanLog to sync.`
            : `${reminder.template.item} · RM ${reminder.template.amount.toFixed(2)} · ${reminder.template.account} · Tap to review.`,
          data: { screen: 'RedCoins', section: 'plan', reminderId: reminder.id },
          sound: true,
        },
        trigger: { type: 'date', date, channelId: CHANNEL },
      }).catch(() => null);
      if (notificationId) reminder.notificationIds.push(notificationId);
    }
  }
}

/** Called only from a visible, user-initiated schedule action. */
export async function requestReminderAccess() {
  if (!Notifications) return;
  await Notifications.setNotificationChannelAsync(CHANNEL, { name: 'RedCoins reminders', importance: Notifications.AndroidImportance.HIGH, sound: 'default' });
  const permission = await Notifications.getPermissionsAsync();
  if (!permission.granted && permission.canAskAgain) await Notifications.requestPermissionsAsync();
}
