import React from 'react';
import { Modal, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { SafeAreaView } from 'react-native-safe-area-context';

const chapters = [
  { version: 'Prolog', date: '13–16 Ogos 2026', title: 'Tatkala jurnal kecil mula bernyawa', story: 'Alkisah, sebelum nama versi dipahat pada batu bersurat, lahirlah sebuah pencatat kalori yang mengenal makanan melalui mata Gemini. Ia belajar menyimpan rekod, menghitung makro, menerima sasaran kalori, menjejak aktiviti dan berat, lalu menyimpan segala amanah ke awan Firebase. Dari bengkel kecil inilah LeanLog menemui bentuk pertamanya.' },
  { version: 'v1.0', date: '16 Ogos 2026', title: 'Pintu kota dibuka', story: 'Maka diumumkanlah LeanLog kepada dunia: sebuah teman ringkas untuk menjejak makanan dan kalori. Belum megah istananya, tetapi cukup kukuh untuk memulakan perjalanan.' },
  { version: 'v1.01', date: '17 Ogos 2026', title: 'Tiga cincin dan sebuah pintu pantas', story: 'Datanglah butang tambah yang dapat dicapai dari segala penjuru. Carta berat memperoleh lembah berwarna, sementara protein, karbohidrat dan lemak memakai tiga cincin kebesaran. Pepijat kecil turut diusir dari kota.' },
  { version: 'v1.1', date: '17 Ogos 2026', title: 'Balairung Today diperhalus', story: 'Cincin makro kekal mengawasi rakyat ketika halaman ditatal. Di daerah Settings, lahir perkakas menyemak kemas kini dan kitab kecil yang menerangkan bagaimana makro dihitung.' },
  { version: 'v1.2', date: '17 Ogos 2026', title: 'Kalendar pertama dibentangkan', story: 'Cincin kalori berhenti mencampur makanan dengan pembakaran. Halaman Progress berubah menjadi kalendar bulanan bertanda merah, hijau dan ungu—makanan, aktiviti dan berat dapat dilihat menurut harinya.' },
  { version: 'v1.2.1', date: '17 Ogos 2026', title: 'Utusan kemas kini tiba sendiri', story: 'Balairung Today disusun semula dengan ring di tengah, empat angka utama dan bar kemajuan. LeanLog juga mula memeriksa versi baharu ketika dibuka, lalu membawa rakyat terus kepada APK di GitHub.' },
  { version: 'v1.2.2', date: '17 Ogos 2026', title: 'Angka-angka kembali ke tempatnya', story: 'Kalori dimakan dan baki diletakkan di kiri, pembakaran dan sasaran di kanan. Makro menunjukkan jumlah semasa berbanding matlamat, manakala rekod harian menceritakan jumlah makan serta bakar dengan lebih terang.' },
  { version: 'v1.3.0', date: '17 Ogos 2026', title: 'Panglima Coach memasuki gelanggang', story: 'Sebuah wilayah baharu bernama Coach dibuka. Pengguna memilih peralatan, Gemini menyusun latihan mingguan, set dan ulangan direkod, timer rehat dibunyikan, lalu sesi disimpan ke awan dan ditandai pada kalendar.' },
  { version: 'v1.3.1', date: '17 Ogos 2026', title: 'Guru dari YouTube dan sesi yang bijaksana', story: 'Setiap latihan memperoleh jalan menuju tutorial. Senaman boleh dibuang atau ditambah ketika sesi berlangsung. Tamat sahaja latihan, AI menganggar tenaga terbakar dan menawarkan untuk mencatatnya sebagai aktiviti sebenar.' },
  { version: 'v1.3.2', date: '18 Ogos 2026', title: 'Zaman percubaan dan Suku Suku Separuh', story: 'Tiga hari percubaan, paywall DuitNow dan lesen berasaskan UID didirikan. Suku Suku Separuh hadir bersama mod nutrisi, cardio timer dan panel pentadbir untuk menjaga pintu langganan.' },
  { version: 'v1.3.3', date: '19 Ogos 2026', title: 'Benteng generasi pertama', story: 'Kerajaan generasi pertama diperkukuh untuk edaran umum. Sistem langganan, laman muat turun, panduan pemasangan dan pentadbiran lesen dipoles sebelum LeanLog menghilang seketika ke bengkel untuk perubahan yang jauh lebih besar.' },
  { version: 'v2.2.0', date: '24 September 2026', title: 'Kepulangan selepas musim yang panjang', story: 'Tanpa melalui v1.4 hingga v2.1, LeanLog pulang sebagai kerajaan baharu. Wajah dan seni bina aplikasi berubah besar; inilah jambatan yang membawa jurnal kesihatan lama menuju dashboard pintar generasi kedua.' },
  { version: 'v2.2.1', date: '24 September 2026', title: 'Tabiat kecil, gaji dan Super-Karen', story: 'Data Home dan widget tidak lagi lupa kalori. Tiny Habits membawa streak dan honest skip, Budget Coach belajar hidup dari gaji ke gaji, kategori boleh dibedah hingga subkategori, dan Super-Karen menerima jadual serta snooze yang benar-benar berfungsi.' },
  { version: 'v2.3.0', date: '25 September 2026', title: 'Rahsia AI dipindah ke kubu belakang', story: 'Kunci Gemini tidak lagi dibawa dalam APK; ia dilindungi oleh Firebase backend. Widget direka semula, Tiny Habits memperoleh laporan, Health Connect mula membawa masuk workout, kalendar diperelok dan berat boleh dicatat ke masa lampau.' },
  { version: 'v2.4.0', date: '25 September 2026', title: 'Para pengawal perbelanjaan diangkat', story: 'Spending Guard menjaga account, kategori dan subkategori, sementara satu pengawal utama boleh dipacak pada widget. Cash Reality membezakan wang yang kelihatan daripada wang yang benar-benar boleh dibelanja. Coach 2.0 pula membawa readiness, sejarah, draft, overload, timer dan padanan Health Connect.' },
  { version: 'v2.5.0', date: '26 September 2026', title: 'Jalan dagang menuju Google Drive', story: 'LeanLog belajar mencari Bluecoins QuickSync di Google Drive dan menyegar data di belakang tabir. Ramalan Budget Coach diperhalus, snooze menjadi lebih manusiawi, berat boleh dibackdate dan widget menerima beberapa pembaikan.' },
  { version: 'v2.5.1', date: '26 September 2026', title: 'Jambatan Drive ditempa semula', story: 'Apabila jalan Expo gagal membaca folder awan, sebuah jambatan Kotlin dibina menggunakan Android DocumentsContract dan ContentResolver. Fail .fydb akhirnya dapat diseberangkan dari Google Drive dengan selamat.' },
  { version: 'v2.6.0', date: '26 September 2026', title: 'Segala khazanah dibawa ke awan', story: 'Cloud backup berkembang daripada beberapa rekod kepada seluruh state penting LeanLog. Fixed Commitments, butiran item Budget Coach, baki kad kredit tepat, Tiny Habits kekal, agenda yang berlalu dicoret, dan tiga Spending Guard menghuni widget.' },
  { version: 'v2.7.0', date: '27 September 2026', title: 'Syiling merah pertama ditempa', story: 'RedCoins memasuki LeanLog sebagai modul wang harian. Ia diasaskan daripada sejarah Bluecoins, sementara pemilih Fixed Commitments memperoleh carian penuh merentas rekod lama.' },
  { version: 'v2.8.0', date: '27 September 2026', title: 'RedCoins menjadi sebuah negeri', story: 'Ledger penuh, dashboard harian, account, kategori, filter, multi-select total dan logger pantas dibina secara native dalam LeanLog. Data baharu mengalir ke Budget Coach dan boleh dieksport sebagai CSV untuk diserahkan semula kepada Bluecoins.' },
  { version: 'v2.8.1', date: '27 September 2026', title: 'Perang menentang kelengahan', story: 'Ledger dijadikan virtualized, carian distabilkan, simpanan logger dipercepat dan arah widget diperbetulkan. Ruang pada widget dipadatkan supaya pengawal perbelanjaan tidak membazir tanah.' },
  { version: 'v2.8.2', date: '27 September 2026', title: 'Setiap ringgit diberi tugas', story: 'Budget subkategori diikat kepada jumlah salary cycle. Fixed Commitments dipamerkan sebagai jangkaan sebelum payday, Home dan ledger RedCoins menjadi interaktif, empat guard dirancang untuk widget, dan kalori mula membezakan sasaran cutting daripada maintenance.' },
  { version: 'v2.8.3', date: '28 September 2026', title: 'Pencatat wang belajar mengingati', story: 'Logger kini mengenal pembelian lama, mengisi harga, account dan kategori, serta menyimpan default mengikut jenis transaksi. Ledger disusun mengikut waktu, carian dan filter dipercepat, empat guard memenuhi grid widget, Budget Allocation dibersihkan, dan inbox lokal mula menangkap cadangan transaksi daripada notifikasi.' },
  { version: 'v2.9.0', date: '28 September 2026', title: 'Bendahara dipercepat, panglima memilih gelanggang', story: 'Ledger RedCoins berpindah ke SQLite agar ribuan transaksi dapat dicari tanpa tersekat. Transaksi masa hadapan, baki account, loan aktif dan eksport Bluecoins diperketat. Di gelanggang Coach, pengguna kini memilih Full Body atau Push–Pull–Legs, menetapkan bilangan sesi dan mengarang Day 1 sendiri sebelum LeanLog menyusun baki minggu.' },
  { version: 'v2.9.1', date: '28 September 2026', title: 'Balairung disatukan, catatan dipermudah', story: 'RedCoins belajar mendamaikan rekodnya dengan khazanah Bluecoins agar satu transaksi tidak lagi muncul sebagai dua bayang. Pintu wang dipindah ke tempat yang lebih wajar, ringkasan harian kembali menurut hari sebenar, dan rancangan bajet dilipat kemas. Di wilayah tubuh, foto cermin bersatu dengan garis masa, catatan berat boleh disorok, manakala Progress, Settings dan pintu logger memakai semula busana LeanLog—tanpa emoji riuh dan kotak-kotak yang terasa asing.' },
];

export default function LeanLogChronicle({ visible, onClose }: { visible: boolean; onClose: () => void }) {
  return <Modal visible={visible} animationType="slide" onRequestClose={onClose}>
    <SafeAreaView style={s.safe}>
      <View style={s.header}><TouchableOpacity onPress={onClose} style={s.back}><Ionicons name="arrow-back" size={22} color="#FFF4DB" /></TouchableOpacity><View style={{ flex: 1 }}><Text style={s.kicker}>ARKIB DIRAJA LEANLOG</Text><Text style={s.headerTitle}>Hikayat sebuah app.</Text></View></View>
      <ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
        <View style={s.hero}><Text style={s.heroMark}>۞</Text><Text style={s.heroTitle}>Hikayat LeanLog</Text><Text style={s.heroCopy}>Maka tersebutlah kisah sebuah pencatat kalori yang enggan duduk diam, lalu membesar menjadi teman makan, senaman, tabiat dan wang.</Text><Text style={s.heroMeta}>DICATAT SEJAK OGOS 2026 · {chapters.length - 1} RELEASE</Text></View>
        <View style={s.thread} />
        {chapters.map((chapter, index) => <View key={chapter.version} style={s.chapter}><View style={[s.seal, index === chapters.length - 1 && s.latestSeal]}><Text style={s.sealText}>{index + 1}</Text></View><View style={[s.parchment, index === chapters.length - 1 && s.latest]}><View style={s.chapterTop}><Text style={s.version}>{chapter.version}</Text><Text style={s.date}>{chapter.date}</Text></View><Text style={s.title}>{chapter.title}</Text><Text style={s.story}>{chapter.story}</Text>{index === chapters.length - 1 && <Text style={s.current}>BAB TERKINI · PERJALANAN MASIH BERTERUSAN</Text>}</View></View>)}
        <View style={s.ending}><Text style={s.endingMark}>✦</Text><Text style={s.endingText}>Syahadan, selagi ada makanan yang belum dicatat, workout yang belum selesai dan perbelanjaan yang perlu dijaga, hikayat ini belum tamat.</Text></View>
      </ScrollView>
    </SafeAreaView>
  </Modal>;
}

const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#101A2B' }, header: { flexDirection: 'row', alignItems: 'center', gap: 13, paddingHorizontal: 17, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: '#29364B' }, back: { width: 42, height: 42, borderRadius: 14, backgroundColor: '#202C40', alignItems: 'center', justifyContent: 'center' }, kicker: { color: '#91DCBB', fontSize: 8, fontWeight: '900', letterSpacing: 1.7 }, headerTitle: { color: '#FFF4DB', fontFamily: 'serif', fontSize: 22, fontWeight: '800', marginTop: 2 }, content: { padding: 16, paddingBottom: 42 }, hero: { backgroundColor: '#F7EEDC', borderRadius: 28, padding: 24, alignItems: 'center' }, heroMark: { color: '#C95370', fontSize: 27 }, heroTitle: { color: '#101A2B', fontFamily: 'serif', fontSize: 37, fontWeight: '800', marginTop: 4 }, heroCopy: { color: '#596173', textAlign: 'center', fontFamily: 'serif', fontSize: 15, lineHeight: 23, marginTop: 10 }, heroMeta: { color: '#C95370', fontSize: 7, fontWeight: '900', letterSpacing: 1.2, marginTop: 17 }, thread: { position: 'absolute', left: 30, top: 250, bottom: 110, width: 2, backgroundColor: '#344158' }, chapter: { flexDirection: 'row', alignItems: 'flex-start', marginTop: 14 }, seal: { width: 29, height: 29, borderRadius: 15, backgroundColor: '#344158', borderWidth: 3, borderColor: '#101A2B', alignItems: 'center', justifyContent: 'center', marginTop: 18, marginRight: 9, zIndex: 2 }, latestSeal: { backgroundColor: '#FF6542' }, sealText: { color: '#FFF4DB', fontSize: 8, fontWeight: '900' }, parchment: { flex: 1, backgroundColor: '#FFF9EA', borderRadius: 19, padding: 15, borderWidth: 1, borderColor: '#E2D7C3' }, latest: { borderColor: '#FF6542', borderWidth: 2 }, chapterTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 }, version: { color: '#C95370', fontSize: 10, fontWeight: '900', letterSpacing: 1 }, date: { color: '#8A8175', fontSize: 7, fontWeight: '800' }, title: { color: '#101A2B', fontFamily: 'serif', fontSize: 18, fontWeight: '800', marginTop: 7 }, story: { color: '#596173', fontFamily: 'serif', fontSize: 12, lineHeight: 19, marginTop: 7 }, current: { color: '#FF6542', fontSize: 7, fontWeight: '900', letterSpacing: 1, marginTop: 12 }, ending: { alignItems: 'center', paddingHorizontal: 28, paddingTop: 28 }, endingMark: { color: '#91DCBB', fontSize: 22 }, endingText: { color: '#AAB5C7', textAlign: 'center', fontFamily: 'serif', fontSize: 13, lineHeight: 20, marginTop: 7 },
});
